### ISSUE TITLE
Create `UserSession` table

### ISSUE THREAD

**Issue by queercat** [queercat/cube#8]
1. Create a new entity `UserSession` with the following members: `Id [Guid], User [Entity Foreign Key], ExpirationDate [DateTime]`
2. Create a new table named `UserSessions` using that entiy.
3. Create a new migration named something like "Adds UserSessions"

**Comment by Or-If** [comment]
[Implemented](https://github.com/queercat/cube/commit/2fdd049d3533595143d9824d6143cb31df3b3537)
